#!/bin/bash

# make fat drive from kernel image and initramfs image.

set -e

HERE="$(dirname "$0")"

LINUX="${1:?}"
RAMFS="${2:?}"
TARGET="${3:?}"
TARGET_SIZE="${4:?}"

IMAGE="$TARGET"/core.img


export MTOOLSRC="$TARGET"/mtoolsrc
echo "drive c: file=\"$IMAGE\" partition=1" > "$MTOOLSRC"

# Create a FAT formatted disk image with one partition.
dd if=/dev/zero of="$IMAGE" count="$TARGET_SIZE" bs=512
mpartition -I c:
mpartition -c -t 88 -h 16 -s 63 c:
mformat c:

# Install grub files including kernel and ramfs images
mmd c:/boot
mmd c:/boot/grub
mcopy /boot/grub/stage1 c:/boot/grub
mcopy /boot/grub/stage2 c:/boot/grub
mcopy /boot/grub/fat_stage1_5 c:/boot/grub
mcopy "$RAMFS" c:/boot/grub
mcopy "$LINUX" c:/boot/grub
mcopy "$HERE"/menu.lst c:/boot/grub/grub.conf

echo "(hd0) $IMAGE" > "$TARGET"/bmap

cat <<EOF |
geometry (hd0) 88 16 63
root (hd0,0)
setup (hd0)
EOF
/sbin/grub --device-map="$TARGET"/bmap --batch

# Remove the intermediate files.
rm "$TARGET"/mtoolsrc "$TARGET"/bmap
