#!/bin/bash

# make fat drive from kernel image and initramfs image.

set -e

HERE="$(dirname "$0")"

LINUX="${1:?}"
RAMFS="${2:?}"
TARGET="${3:?}"


echo "drive c: file=\"$TARGET/core.img\" partition=1" > "$TARGET"/mtoolsrc
export MTOOLSRC="$TARGET"/mtoolsrc

dd if=/dev/zero of="$TARGET"/core.img count=088704 bs=512
mpartition -I c:
mpartition -c -t 88 -h 16 -s 63 c:
mformat c:

mmd c:/boot
mmd c:/boot/grub

# install grub files
mcopy /boot/grub/stage1 c:/boot/grub
mcopy /boot/grub/stage2 c:/boot/grub
mcopy /boot/grub/fat_stage1_5 c:/boot/grub
mcopy "$RAMFS" c:/boot/grub
mcopy "$LINUX" c:/boot/grub
mcopy "$HERE"/menu.lst c:/boot/grub/grub.conf

echo "(hd0) $TARGET/core.img" > "$TARGET"/bmap

cat <<EOF |
geometry (hd0) 88 16 63
root (hd0,0)
setup (hd0)
EOF
/sbin/grub --device-map="$TARGET"/bmap --batch

# Remove the intermediate files.
rm "$TARGET"/mtoolsrc "$TARGET"/bmap
