#!/bin/sh

echo Starting IOC

IOC="$(hostname)"
REDIRECT_TABLE=/dls_sw/prod/etc/redirector/redirect_table
COMMAND="$(sed -n "/^$IOC /"'{s///; p;}' $REDIRECT_TABLE)"
if [ -n "$COMMAND" ]; then
    su -c "$COMMAND" epics
else
    echo >&2 Unable to find IOC "$IOC"
    exit 1
fi
