#!/bin/bash

# Top level rootfs builder.  This calls the makefile scripts that do the real
# work.

ROOTFS_TOP="$(cd "$(dirname "$0")"; pwd)"

. "$ROOTFS_TOP"/scripts/functions


usage()
{
    cat <<EOF
Usage: rootfs [<options>] <action> [<arguments>]

Invokes the appropriate rootfs action.  The following actions are available:

    help
        Shows this help message

    toolkit
        Builds the toolkit.  Only needs to be done once.

    docs
        Builds the documentation

    all
        Builds all configured packages for selected target.

    package <package>
        Invokes make for selected package and target: must specify <package>
        on command line.

    make
    rootfs
        Assembles the configured rootfs for the selected target.

    imagename
    imagedir
        Prints the full path to the generated rootfs .cpio image or the image
        directory.

The following options can be passed before any action:

    -t<target>
        This overrides the TARGET option set in CONFIG.local.

    -r<build-root>
        This overrides the default definition of ROOTFS_ROOT and the value set
        in CONFIG.local.
EOF
}


EXTRA_OPTIONS=()

call_make()
{
    MAKEFILE="$1"
    shift
    make -f "$ROOTFS_TOP"/scripts/makefiles/"$MAKEFILE" \
        ROOTFS_TOP="$ROOTFS_TOP" "$@" "${EXTRA_OPTIONS[@]}"
}


while getopts 't:r:h' option; do
    case "$option" in
    t)  EXTRA_OPTIONS=("${EXTRA_OPTIONS[@]}" TARGET="$OPTARG") ;;
    r)  EXTRA_OPTIONS=("${EXTRA_OPTIONS[@]}" ROOTFS_ROOT="$OPTARG") ;;
    h)  usage
        exit 0 ;;
    *)  Error 'Invalid option: try -h for help' ;;
    esac
done
shift $((OPTIND-1))

action="$1"
shift

MAKEFILE=
case "$action" in
    h|help)
        usage
        ;;

    docs)
        make -C "$ROOTFS_TOP"/docs ;;

    toolkit)
        call_make TOOLKIT_MAKE "$@" ;;

    a|all)
        call_make ALL_PACKAGES "$@" ;;

    p|package)
        PACKAGE="$1"
        shift
        call_make PACKAGE_MAKE PACKAGE="$PACKAGE" "$@" ;;

    m|make|rootfs)
        call_make ROOTFS_MAKE "$@" ;;

    imagename)
        call_make ROOTFS_MAKE -s --no-print-directory imagename "$@" ;;

    imagedir)
        call_make ROOTFS_MAKE -s --no-print-directory imagedir "$@" ;;

    *)  Error 'Unknown action.  Try `rootfs help` for help' ;;
esac
