#!/bin/bash

# Top level rootfs builder.  This calls the makefile scripts that do the real
# work.

ROOTFS_TOP="$(cd "$(dirname "$0")"; pwd)"

. "$ROOTFS_TOP"/scripts/functions


call_make()
{
    MAKEFILE="$1"
    shift
    make -f "$ROOTFS_TOP"/scripts/makefiles/"$MAKEFILE" \
        ROOTFS_TOP="$ROOTFS_TOP" "$@"
}



action="$1"
shift


MAKEFILE=
case "$action" in
    h|help)
        cat <<EOF
Usage: rootfs <action> [<arguments>]

Invokes the appropriate rootfs action.  The following actions are available:

    help
        Shows this help message

    docs
        Builds the documentation

    all
        Builds all configured packages for selected target.

    package <package>
        Invokes make for selected package and target: must specify <package>
        on command line.

    make
    rootfs
        Assembles the configured rootfs for the selected target.

    imagename
    imagedir
        Prints the full path to the generated rootfs .cpio image or the image
        directory.
EOF
        ;;

    docs)
        make -C "$ROOTFS_TOP"/docs ;;

    a|all)
        call_make ALL_PACKAGES "$@" ;;

    p|package)
        PACKAGE="$1"
        shift
        call_make PACKAGE_MAKE PACKAGE="$PACKAGE" "$@" ;;

    m|make|rootfs)
        call_make ROOTFS_MAKE "$@" ;;

    imagename)
        call_make ROOTFS_MAKE -s --no-print-directory imagename "$@" ;;

    imagedir)
        call_make ROOTFS_MAKE -s --no-print-directory imagedir "$@" ;;

    *)  Error 'Unknown action.  Try `rootfs help` for help' ;;
esac
