#!/bin/sh

# Expects to be called with the following environment variables set:
#
#   KERNEL_NAME     Name of kernel to load from tftp server
#   KERNEL_ADDR     Where to load the kernel into memory
#   BOOTARGS        Arguments to pass as bootargs
#   QUOTE_BOOTARGS  Whether to quote bootargs (depends on target u-boot!)
#   NFS_IP_STRING   IP address of NFS server
#   NFS_NFSROOT     Path to root on NFS server

TARGET="${1:?Target file}"

BOOTARGS="$BOOTARGS root=/dev/nfs nfsroot=$NFS_NFSROOT ip=$NFS_IP_STRING"
(($QUOTE_BOOTARGS))  &&
    BOOTARGS=\""$BOOTARGS"\"

cat <<EOF >"$TARGET"
echo 'Built: $(date)'
tftpboot $KERNEL_ADDR $KERNEL_NAME
setenv bootargs $BOOTARGS
bootm $KERNEL_ADDR
EOF
