#!/bin/sh

# Expects to be called with the following environment variables set:
#
: ${KERNEL_NAME:?}     # Name of kernel to load from tftp server
: ${KERNEL_ADDR:?}     # Where to load the kernel into memory
: ${IMAGE_NAME:?}      # Name of rootfs image to load from tftp server
: ${IMAGE_ADDR:?}      # Where to load the rootfs image into memory
: ${BOOTARGS:?}        # Arguments to pass as bootargs

TARGET="${1:?Target file}"
IMAGE_FILE="${2:?Image file}"

IMAGE_SIZE=$(stat -c %s "$IMAGE_FILE")

BOOTARGS="$BOOTARGS rdinit=/sbin/init root=/dev/ram"
BOOTARGS="$BOOTARGS initrd=0x$IMAGE_ADDR,$IMAGE_SIZE"

cat <<EOF >"$TARGET"
echo 'Built: $(date)'
tftpboot $KERNEL_ADDR $KERNEL_NAME
tftpboot $IMAGE_ADDR $IMAGE_NAME
setenv bootargs "$BOOTARGS"
bootm $KERNEL_ADDR
EOF
