#!/bin/sh

# Create all the devices.  Before we populate /dev we need to have /proc and
# /sys mounted: see busybox/docs/mdev.txt.
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs mdev /dev
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s

# The following devices actually come from /proc and aren't managed by mdev.
ln -s /proc/self/fd /dev/fd
ln -s fd/0 /dev/stdin
ln -s fd/1 /dev/stdout
ln -s fd/2 /dev/stderr

# The /dev/pts directory also isn't managed by mdev
mkdir /dev/pts
mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts
# Finally the /dev/shm directory -- don't know if we need this.
mkdir /dev/shm
mount -t tmpfs -o nosuid,nodev devshm /dev/shm
