#!/bin/sh

# See busybox/docs/mdev.txt for background to the operations here.

# Mount all the mount points required for mdev
sed '/^#/d; /^$/d' /etc/fstab.mdev |
while read name mount type options; do
    mkdir -p $mount
    mount -t $type -o $options $name $mount
done

# The following devices actually come from /proc and aren't managed by mdev.
ln -s /proc/self/fd /dev/fd
ln -s fd/0 /dev/stdin
ln -s fd/1 /dev/stdout
ln -s fd/2 /dev/stderr

# Ask mdev to serialise hotplug events: this is normally what we want, and is a
# lot safer than not serialising.
echo >/dev/mdev.seq

# /dev is ready and waiting to be filled.  Get mdev to populate it.
if [ -f /proc/sys/kernel/hotplug ]; then
    echo /sbin/mdev >/proc/sys/kernel/hotplug
else
    mdev -d
fi
mdev -s
