#!/bin/sh

export PATH

# System initialisation script.  We send everything to logger.
{
    # If we're uninitialised, now's the time to run the initial script.
    [ -x /etc/first-time.sh ]  && /etc/first-time.sh

    # Run all the scripts linked in rc.d
    for script in /etc/rc.d/S*; do
        $script start
    done
} 2>&1 |
logger -s -t rc 
