#!/bin/sh

# System initialisation script run before starting the console.  At this
# point all we really want to do is ensure all the devices are created and
# logging has started.

export PATH

# Before anything else we must:
/etc/init.d/makedevs            #   1. populate /dev
mount -a -t nonfs               #   2. mount what we need for logging
/etc/init.d/syslogd start       #   3. start logging
