#!/bin/sh

. /etc/init.d/functions

SYSLOGD_OPTIONS=
[ -r /etc/syslogd ]  &&  . /etc/syslogd

do_start_stop "$1" /sbin/syslogd -p /var/run/syslogd.pid -- $SYSLOGD_OPTIONS
do_start_stop "$1" /sbin/klogd
