#!/bin/sh

# This script should only be run to create a production release of rootfs.

Error() { echo >&2 "$@"; exit 1; }

RELEASE="${1:?Specify release number}"

GIT_REPO=https://gitlab.diamond.ac.uk/controls/targetOS/rootfs.git
PROD_DIR=/dls_sw/prod/targetOS/rootfs
DLS_EPICS_RELEASE=3.14.12.7

# Prevent accidents.  If you get past this it's all your own fault!
[[ "$2" = confirm ]]  ||  Error Must confirm release


RELEASE_JOB="
    git clone --depth 1 --branch $RELEASE $GIT_REPO $RELEASE  &&
    cd $RELEASE  &&
    scripts/release/build-release"
queue-job -R$DLS_EPICS_RELEASE -b -C "$PROD_DIR" -N "$RELEASE_JOB"
