#!/bin/sh

# Expects to be called with the following environment variables set:
#
: ${KERNEL_NAME:?}     # Name of kernel to load from tftp server
: ${KERNEL_ADDR:?}     # Where to load the kernel into memory
: ${NFS_SERVER:?}      # Name of NFS server
: ${NFS_ROOTFS:?}      # Path to rootfs on NFS server
: ${BOOTARGS:?}        # Extra arguments to pass as bootargs

TARGET="${1:?Target file}"

NFS_NFSROOT="$(host "$NFS_SERVER" | sed 's/^.*address //'):$NFS_ROOTFS"
NFS_IP_STRING='$ipaddr::$gatewayip:$netmask:$hostname::none'

BOOTARGS="$BOOTARGS root=/dev/nfs nfsroot=$NFS_NFSROOT ip=$NFS_IP_STRING ro"

cat <<EOF >"$TARGET"
echo 'Built: $(date)'
tftpboot $KERNEL_ADDR $KERNEL_NAME
setenv bootargs "$BOOTARGS"
bootm $KERNEL_ADDR
EOF
