TOP = $(CURDIR)/../..
include $(CURDIR)/../COMMON
include $(CURDIR)/../EXTRAS

nologin_VERSION = local

build-local: nologin

install:
	$(install) -m 555 $(O)/nologin /sbin




include $(CURDIR)/../RULES
