#!/bin/sh

# Start and stop ntp daemon

. /etc/init.d/functions

do_start()
{
    ntpdate -b $(sed -n '/^server /{s///;p;}' /etc/ntp.conf)
    start-stop-daemon -S -x $program "$@"
}

do_start_stop "$1" /usr/sbin/ntpd -p /var/run/ntpd.pid -- -g
