#!/bin/sh

# Start and stop ntp daemon

. /etc/init.d/functions

TIMESERVERS="$(sed -n '/^server /{s///;p;}' /etc/ntp.conf)"

do_start()
{
    # First try and get a sensible synchronisation using rdate
    for TIMESERVER in $TIMESERVERS; do
        echo -n Setting time from $TIMESERVER ...
        if rdate -s $TIMESERVER; then
            echo -n ' ok...'
            break
        fi
    done

    start-stop-daemon -S -x $program "$@"
}

do_start_stop "$1" /usr/sbin/ntpd -p /var/run/ntpd.pid -- -g
