#!/bin/sh

mount -t tmpfs tmpfs /dev
makedevs -d /etc/device_table /dev

# The following devices actually come from /proc
ln -s /proc/self/fd /dev/fd
ln -s fd/0 /dev/stdin
ln -s fd/1 /dev/stdout
ln -s fd/2 /dev/stderr

# Mount the remaining file systems
mkdir /proc /sys /tmp 
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /tmp
