#!/bin/sh

# System initialisation script.



# Run all the scripts linked in rc.d
for script in /etc/rc.d/S*; do
    $script start
done

mount -a
/sbin/ldconfig


# Still to do:
# * Perform the nfs mounts in their own startup script.
# * Possibly move more stuff into fstab and mount in an rc.d script.
# * Run logger so that the rc output goes into syslog.  Clearly can't start
#   this until syslogd is running, and have to have /dev initialised first.
