#!/bin/sh

# System initialisation script.

# Mount the core file systems
/etc/init.d/makedevs
# Get syslog up and running
/sbin/syslogd
# also klogd ?
# /sbin/klogd
# Freshen the ldconfig cache
/sbin/ldconfig

# Finally get the network running
/etc/init.d/network start

mount -a

# Run all the scripts linked in rc.d
for script in /etc/rc.d/*; do
    $script start
done

inetd
