#!/bin/sh

# This needs to be called once during boot to ensure that the u-boot
# configuration ethernet address is set as the MAC address -- for some reason
# this isn't picked up by Linux from wherever the hardware keeps it.

BOOT_CONFIG="$(tail -c+5 /dev/mtd1ro | tr '\0' '\n' | sed '/^$/q')"

boot_config()
{
    echo "$BOOT_CONFIG" |
    sed -n "/^$1=/{s///;p;q;}"
}

ifconfig eth0 hw ether $(boot_config ethaddr)
