#!/bin/sh

# Adds commands to be executed on initialisation.
#
# The following environment variable must be set:
#
: ${sysroot:?}      # Target rootfs, where to install files

FIRST_TIME="$sysroot"/etc/first-time.sh


if [ "$1" = -c ]; then
    # This is called to wrap up the file.  Only do the wrap-up if it was
    # created in the first place.
    if [ -e "$FIRST_TIME" ]; then
        cat <<EOF >>"$FIRST_TIME"
rm /etc/first-time.sh
mount -o remount,ro /
EOF
    fi
else
    if ! [ -e "$FIRST_TIME" ]; then
        # If this is the first call of this function then insert the first-time
        # header.
        cat <<EOF >"$FIRST_TIME"
#!/bin/sh
echo Performing first boot initialisation
mount -o remount,rw /
EOF
        chmod +x
    fi

    echo "$@" >>"$FIRST_TIME"
fi
