#!/bin/bash

# Adds commands to be executed on initialisation.
#
# The following environment variable must be set:
#
: ${sysroot:?}      # Target rootfs, where to install files

FIRST_TIME="$sysroot"/etc/first-time.sh


if [ "$1" != -c ]; then
    if ! [ -e "$FIRST_TIME" ]; then
        # If this is the first call of this function then insert the first-time
        # header.
        cat <<'EOF' >"$FIRST_TIME"
#!/bin/sh
if [[ "$0" != /tmp/first-time.sh ]]; then
    cp "$0" /tmp/first-time.sh
    exec /tmp/first-time.sh
fi
echo Performing first boot initialisation
rootfsro="$(mount | grep ' / .*[(,]ro[,)]')"
[ -n "$rootfsro" ]  &&  mount -o remount,rw /
EOF
    fi

    echo "$@" >>"$FIRST_TIME"
else
    # This is called to wrap up the file.  Only do the wrap-up if it was
    # created in the first place.
    if [ -e "$FIRST_TIME" ]; then
        cat <<'EOF' >>"$FIRST_TIME"
rm -f /etc/first-time.sh
[ -n "$rootfsro" ]  &&  mount -o remount,ro /
EOF
        chmod +x "$FIRST_TIME"
    fi
fi
