#!/bin/sh

# Add new group to /etc/group, emulating groupadd(8).
#
# Usage: groupadd <sysroot> -g <gid> <new-group>
#
# The -g flag is mandatory.
#
# The environment variable sysroot must be set to point to the target rootfs.

HERE="$(dirname "$0")"

GID=

while getopts 'g:' option; do
    case "$option" in
        g)  GID=$(($OPTARG)) ;;
        *)  exit 1 ;;
    esac
done
shift $((OPTIND-1))

NAME="${1:?}"

echo "$NAME:*:$GID:" >>$sysroot/etc/group
