#!/bin/bash

# Install a file in target root filesystem.  Called as:
#
#   ./install [options] <file> <target-dir>
#
# with the following environment variable set:
#
: ${sysroot:?}          # Path to rootfs being built
: ${install_list:?}     # Used to record list of installed executables
: ${fakeroot_list:?}    # Used to record list of fakeroot commands
#
# The CROSS_COMPILE envrionment variable should also be set, but it can be
# empty for a native build.
#
# Here <target-dir> is relative to <sysroot> and the given permissions are
# set if specified.
#
# The following options are supported:
#
#   -s      Strip file and mark as executable
#   -x      Mark code as executable, but don't strip
#   -m:     Set mode
#   -o:     Set owner
#   -g:     Set group
#   -f      Destination is file name, not directory: only one file can be
#           copied in this case.
#   -l      Create soft links to arguments instead of copying files.
#   -d      Treat arguments as directories to be created

set -o pipefail


HERE="$(dirname "$0")"

. "$HERE"/functions

maybe_set_mode()
{
    if [ -n "$MODE" ]; then
        chmod "$MODE" "$1";
    fi  &&
    if [ -n "$OWNER" -o -n "$GROUP" ]; then
        do_root chown "$OWNER:$GROUP" "$1"
    fi
}


DO_STRIP=0
EXECUTABLE=0
MODE=
OWNER=
GROUP=
FILENAME=0
SOFT_LINKS=0
MKDIR=0

while getopts 'sxm:o:g:fld' option; do
    case "$option" in
        s)  DO_STRIP=1
            EXECUTABLE=1 ;;
        x)  EXECUTABLE=1 ;;
        m)  MODE="$OPTARG" ;;
        o)  OWNER="$OPTARG" ;;
        g)  GROUP="$OPTARG" ;;
        f)  FILENAME=1 ;;
        l)  SOFT_LINKS=1 ;;
        d)  MKDIR=1 ;;
        *)  Error Invalid switch ;;
    esac
done
shift $((OPTIND-1))

# The MKDIR option behaves differently from all the other options.
if ((MKDIR)); then
    ((!FILENAME  &&  !SOFT_LINKS  &&  !DO_STRIP  &&  !EXECUTABLE))  ||
        Error Inconsistent options for -d
    for dir; do
        mkdir -p "$sysroot/$dir"  &&
        maybe_set_mode "$sysroot/$dir"  ||  exit
    done
    exit
fi

# Argument checking for normal case
if (($# < 2)); then
    Error Missing arguments
elif ((FILENAME && $# != 2)); then
    Error Cannot specify multiple files with filename target
fi

# Some bash trickery to get at the list of arguments.  Want to iterate over
# all of the files -- except for the last one!
args=("$@")
target_dir="$sysroot/${args[$#-1]}"
unset args[$#-1]

for source in "${args[@]}"; do
    if ((FILENAME)); then
        target="$target_dir"
    else
        target="$target_dir/$(basename "$source")"
    fi
    [ -e "$target" -o -L "$target" ]  &&  Error File "$target" already exists

    if ((SOFT_LINKS)); then
        ln -s "$source" "$target"
    elif [ -d "$source" ]; then
        Error Cannot install directory "$source"
    elif link="$(readlink "$source")"; then
        ln -s "$link" "$target"
    else
        cp "$source" "$target"  &&
        if ((EXECUTABLE)); then
            echo "$target" >> $install_list  &&
            if ((DO_STRIP)); then
                MODE="${MODE:-$(stat -c%a "$source")}"  &&
                do_strip "$target"
            fi
        fi  &&
        maybe_set_mode "$target"
    fi || exit
done
