#!/bin/sh

# Install a file in target root filesystem.  Called as:
#
#   ./install [options] <file> <target-dir> [<permissions>]
#
# with the following environment variables set:
#
#   COMPILER_PREFIX
#   sysroot             Path to rootfs being built
#
# Here <target-dir> is relative to <sysroot> and the given permissions are
# set if specified.
#
# The following options are supported:
#
#   -s      Strip file if appropriate
#   -m:     Set mode
#   -o:     Set owner
#   -g:     Set group

HERE="$(dirname "$0")"

. "$HERE"/functions

install_file "$@"
