#!/bin/bash

# Script to install busybox

set -e

TARGET="${1:?}"
BUSYBOX_DIR="${2:?}"

# Install busybox files
echo 'Installing busybox files'
cp "$BUSYBOX_DIR"/busybox "$TARGET"/bin/
chmod 555 "$TARGET"/bin/busybox
chmod u+s "$TARGET"/bin/busybox

cat "$BUSYBOX_DIR"/busybox.links |
grep -v /linuxrc |
while read -r; do
    ln -s /bin/busybox "$TARGET"/"${REPLY:1}" 
done
