#!/bin/sh

TARGET="${1:?Target file}"
KERNEL_IMAGE="${2:?Kernel image}"
BOOTARGS="${3}"
NFSROOT="${4:?}"
NFSIP="${5:?}"

KERNEL_ADDR=a0001000
BOOTARGS="$(echo \
    "$BOOTARGS" \
    root=/dev/nfs \
    nfsroot=$NFSROOT \
    ip=$NFSIP)"

cat <<EOF >"$TARGET"
echo 'Built: $(date)'
tftpboot $KERNEL_ADDR $KERNEL_IMAGE
setenv bootargs "\$bootargs $BOOTARGS"
bootm $KERNEL_ADDR
EOF
