#!/bin/sh
# Simple populate script: simply populates from a hard-wired list.

HERE="$(dirname "$0")"

# sysroot="${1:?}"
# BINUTILS_DIR="${2:?}"
# COMPILER_PREFIX="${3:?}"
# TERMS="${4}"

. "$HERE"/functions

# We have two notions of sysroot here.  $sysroot is the root of the *target*
# filesystem that we're building, while $SYSROOT defined here is the glibc
# sysroot: in effect we're copying $SYSROOT -> $sysroot.
SYSROOT="$BINUTILS_DIR/$COMPILER_PREFIX/sys-root"

READELF="$COMPILER_PREFIX-readelf"


LIB_FILES='
    ld
    libc
    libcrypt
    libdl
    libgcc_s
    libm
    libpthread
    libresolv
    libnsl
    libnss_compat
    libnss_dns
    libnss_files
    libnss_nis
    librt
    libstdc++
    libutil'

USR_LIB_FILES='
    libncurses'

SO_FILES='.so -*.so .so.*'


# Performs the easy half of the work done by ldconfig: creates the
# appropriate soft links.
#
#   link_lib dir file
#
link_lib()
{
    local target_dir="$sysroot/$1"
    local target_file="$(basename "$2")"
    SONAME="$(
        "$READELF" -d "$target_dir/$target_file" |
        sed -rn '/\(SONAME\)/{s/^.*\[(.*)\]/\1/; p;}' )"  &&
    [ -e "$target_dir/$SONAME" ]  ||
        ln -s "$target_file" "$target_dir/$SONAME"
}

    
# Copies list of libraries into specified target directory
#
#   populate target-dir lib-list
#
populate()
{
    local dir="$1"
    shift
    
    for prefix; do
        local found=0
        for suffix in $SO_FILES; do
            for file in "$SYSROOT/$dir/$prefix"$suffix; do
                if [ -f "$file"  -a  ! -L "$file" ]; then
                    found=1
                    install_file -m-w "$file" /$dir  &&
                    link_lib $dir "$file" ||
                        return 1
                fi
            done
        done
        
        if ! ((found)); then
            echo -n "Library $prefix not found"
            return 1
        fi
    done
}


install_terminfo()
{
    for term; do
        local dir=/usr/share/terminfo/${term::1}  
        mkdir -p "$sysroot/$dir"  &&
        cp "$SYSROOT/$dir/$term" "$sysroot/$dir"  ||  return 1
    done
}


populate lib $LIB_FILES  &&
populate usr/lib $USR_LIB_FILES  &&

# /sbin/ldconfig -v -r "$sysroot"  &&

install_terminfo $TERMS
