#!/bin/sh
# Simple populate script: simply populates from a hard-wired list.

HERE="$(dirname "$0")"

sysroot="${1:?}"
BINUTILS_DIR="${2:?}"
COMPILER_PREFIX="${3:?}"
TERMS="${4}"

. "$HERE"/functions

# We have two notions of sysroot here.  $sysroot is the root of the *target*
# filesystem that we're building, while $SYSROOT defined here is the glibc
# sysroot: in effect we're copying $SYSROOT -> $sysroot.
SYSROOT="$BINUTILS_DIR/$COMPILER_PREFIX/sys-root"


LIB_FILES='
    ld
    ld-linux
    libc
    libcrypt
    libdl
    libgcc_s
    libm
    libpthread
    libresolv
    libnsl
    libnss_compat
    libnss_dns
    libnss_files
    libnss_nis
    librt
    libstdc++
    libutil'

USR_LIB_FILES='
    libncurses'

SO_FILES='.so .so.*'


    
# Copies list of files into specified target directory
#
#   populate target-dir lib-list [suffixes]
#
populate()
{
    local dir="$1"
    local suffixes="$3"
    local prefix suffix file

    for prefix in $2; do
        if [ -n "$suffixes" ]; then
            local found=0
            for suffix in $suffixes; do
                for file in "$SYSROOT/$dir/$prefix"$suffix; do
                    if [ -e "$file" ]; then
                        install_file -m-w $file /$dir || return 1
                        found=1
                    fi
                done
            done
            if ! ((found)); then
                echo -n File "$prefix"
                [ -n "$suffixes" ]  && echo -n "[$suffixes]"
                echo " not found"
                return 1
            fi
        else
            install_file -m-w "$SYSROOT/$dir/$prefix" /$dir
        fi
    done
}


# Special hack to search /usr/lib for links to /lib.
link_usr_lib()
{
    local file link

    for file in "$SYSROOT/usr/lib"/*; do
        if link="$(readlink "$file")"  &&
           grep -q '^\.\./\.\./lib' <<<"$link"  &&
           [ -e "$sysroot/usr/lib/$link" ]; then
            ln -s "$link" "$sysroot/usr/lib/$(basename "$file")"  
        fi  ||  return 1
    done
}


install_terminfo()
{
    for term; do
        local dir=/usr/share/terminfo/${term::1}  
        mkdir -p "$sysroot/$dir"  &&
        cp "$SYSROOT/$dir/$term" "$sysroot/$dir"  ||  return 1
    done
}


populate lib "$LIB_FILES" "-2.7.so $SO_FILES"  &&
populate usr/lib "$USR_LIB_FILES" "$SO_FILES"  &&
link_usr_lib  &&

populate sbin ldconfig &&

install_terminfo $TERMS
